#TODO  - Настроить параметры безопасности и JWT.
#TODO  - Включить Swagger UI.

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    username: dbuser
    url: jdbc:mysql://localhost:3306/bankcards
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: true

security:
  jwt:
    secret_key: dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC0yMDI0
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days
schedule:
  interval-in-cron: 0 5 0 * * *

logging:
  level:
    com:
      example: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
          JpaTransactionManager: DEBUG