#TODO  - Настроить параметры безопасности и JWT.
#TODO  - Включить Swagger UI.

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    username: dbuser
    url: jdbc:mysql://localhost:3306/bankcards
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: false

logging:
  level:
    com:
      example: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
          JpaTransactionManager: DEBUG